version: "3"
services:
  questions-fastapi-db:
    image: postgres:14
    ports:
      - "5432:5432"
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_SERVER=questions-fastapi-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=questions-fastapi
    restart: always

  questions-fastapi:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - questions-fastapi-db
    ports:
      - "8000:8000"
    volumes:
      - ./:/src
    environment:
      - DATABASE_DSN=postgresql://postgres:password@questions-fastapi-db:5432/questions-fastapi
      - BACKEND_CORS_ORIGINS=["http://localhost:3000","http://localhost:8000"]
    command: sh -c "alembic upgrade head && uvicorn --host 0.0.0.0 --port 8000 src.main:app"
    restart: always

volumes:
  app-db-data:
